### ISSUE TITLE
Typos on Page 68

### ISSUE THREAD

**Issue by YiyueMaggieMao** [aaknop/I2DM#118]
- Cases where n==1 (mod) should be n==1(mod 4), same for n==2 and n==3
- It is more respectful to reference a player as "they/them", rather than "it"

**Comment by alexanderknop** [comment]
I was not able to find where I address players via "it". Could you please point the location of this?

**Comment by YiyueMaggieMao** [comment]
Top of page 68:
"The player that makes the first move... so IT loses after ITS turn", and "the first player to move wins since IT can take a chip..."
