### ISSUE TITLE
Some issues on Page 4 of I2DM.pdf

### ISSUE THREAD

**Issue by alexnguo** [aaknop/I2DM#2]
_Note: This does not cover all of the issues on the 4th page of I2DM.pdf_

Exercise 1.1:

"But in order to prove it we need to know something again, it is a problem!" --> "But in order to prove it **,** we need to know something again, **which** is a problem!"

Also, make the **"it"** more clear. Do you mean proving a **"statement"** in this case?

"But what it means to know something?" --> "But what **does** it mean to know something?"

"An axiom is a statement that believed to be true" --> "An axiom is a statement that **is** believed to be true"

Make sure to change all of your **iff** on the page to **if**. (unless if I am misunderstood)

Overall, you are on a good path to publishing a Discrete Mathematics textbook in the future. 👍 

- Alex Guo (Username: aguo)

**Comment by liuhanshu2000** [comment]
I think iff means "if and only if" here. It's been used in my other math classes as well.

**Comment by alexnguo** [comment]
Ah, that makes sense now!

**Comment by alexnguo** [comment]
Yes, the textbook says "sometimes, authors will write "iff" as an abbreviation for **if and only if.**"

**Comment by alexanderknop** [comment]
Thank you for your comments! 
liuhanshu2000 is right and iff is an abbreviation for "if and only if".
