### ISSUE TITLE
Few suggestions chapter_1_proofs.tex

### ISSUE THREAD

**Issue by kar2** [aaknop/I2DM#3]
Found a few places to consider changes in chapter_1_proofs.tex:

Line 27: should be “each of them is true”
Line 30: change “whether” to “when”
Line 68: change to “But what does it mean to know something?”
Line 70: may want to add “so” before “it”
Line 72: add “is” before “believed”
Line 160: add “a” before “statement”
Line 166: change “to” to “too”
Suggestion: The sentence beginning with “Add problem arising…” on line 165 is a little bit confusing.
Line 168: Change to “we are going to discuss one approach to this in the second part of this book.”

Found by Kartik Nighojkar

**Comment by alexanderknop** [comment]
Thank you!
