### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by OwenPi** [aaknop/I2DM#35]
1. in exercise 4.4, I think "A==>B is the same as (A==>B)/\(B==>A)" should be changed to "A<==>B is the same as (A==>B)/\(B==>A)"

2. is the page ordering of Chapter 5 wrong?

Zhiqiang Pi (zhpi@ucsd.edu)

**Comment by alexanderknop** [comment]
I don't see anything wrong with the page order...

**Comment by OwenPi22** [comment]
Page 28 is after page 32 in the pdf

**Comment by OwenPi** [comment]
> I don't see anything wrong with the page order...

Page 28 is after page 32 in the pdf

**Comment by alexanderknop** [comment]
No, it is 33 as it supposed to be... Could you send a screenshot?

**Comment by OwenPi** [comment]
> No, it is 33 as it supposed to be... Could you send a screenshot?

I'm not sure how to show you, but now I see page 29 after page 22, page 23 after page 32, and page 27 and page 28 after page 26

**Comment by OwenPi** [comment]
> No, it is 33 as it supposed to be... Could you send a screenshot?

I can see that it is correct in the code, but somehow the way that it is displayed on my computer in wrong.

**Comment by OwenPi** [comment]
![untitled](https://user-images.githubusercontent.com/30527895/53126717-a4fadc80-3515-11e9-9096-b318ae898110.png)

**Comment by OwenPi** [comment]
this is what I see on my laptop

**Comment by OwenPi** [comment]
![untitled](https://user-images.githubusercontent.com/30527895/53126813-d673a800-3515-11e9-8f68-3e0540f79d1f.png)

**Comment by alexanderknop** [comment]
Oh, thank you! It seems that the problem is inside Safari (I've just checked and I have the same issue); however, if you open the page in chrome, everything is fine.
