### ISSUE TITLE
Possible typos

### ISSUE THREAD

**Issue by OwenPi** [aaknop/I2DM#46]
1. in part 6.3 the definition of a graph, I believe the second property should be (x,y1) is in D and (x,y2) is in D. (Sorry I don't know LaTex)
2. in part 6.4 before definition 6.2, I think "f: X -> Y" might be better than "f: X to Y"
3. in definition 6.2 before theorem 6.2, I don't think the last sentence of the first bullet point in clear
4. on the bottom of page 51, in the set of the second last line, I think the brackets are off
5. in the proof of theorem 8.4 I think |Y| = n instead of m

Zhiqiang Pi (zhpi@ucsd.edu)

**Comment by alexanderknop** [comment]
No worries, I am sorry it took me that long to answer.

> on the bottom of page 51, in the set of the second last line, I think the brackets are off
I do not see anything wrong with them
