### ISSUE TITLE
Typo/Mistake Suggestions 

### ISSUE THREAD

**Issue by Will-Hsu** [aaknop/I2DM#5]
These are some suggestions I found in I2DM pdf:
(pg3) 1. The three statements about salmon to be written as three sentences, w/ a capital letter and a 
               period. ex) If a salmon has scales, it has fins.
(pg4) 2. consider explaining what iff means ex) if and only if(iff)
           3. in exercise 1.1 - 1 the question asks "if n^2 is positive implies n is not equal to 0" while the 
               solution only reach the conclusion that "we prove that if n doesn't equal to 0, then n^2>0" 
               consider switching the order of the two parts in the question
          4. exercise 1.1 -2 isn't answered while the solution to 1.1-1 is put under 1.1-2, consider moving it 
              before 1.1 -2
(pg5) 5. header(1.2.........) is visible on this page but not on other pages
          6. the first P in sec 1.2 line 2, add by before starting----->"is to try to prove (by) starting...."
          7. 2nd P in line 2. add a comma after For example(,)
          8. bottom paragraph line 3----> By applying axiom 3 twice
(pg6)10. 1st line, "in this paragraph"? should it be "in this section" or "in the previous section"
          11. the last line of the 1st paragraph, considering adding chapter numbers to show what "second 
                part of this book" is

William Hsu(whsu@ucsd.edu)

**Comment by alexanderknop** [comment]
Thank you for your comments. 
I decided to keep the first statement about the salmon as is and I do not understand what solution you are talking about (all the exercises are without solutions). As about the header, it is a book style, chapter names are only on odd pages. It also seems that "by" is not necessary in section 1.2.
