### ISSUE TITLE
Ch. 8 Typos and Suggestions

### ISSUE THREAD

**Issue by jason-vega** [aaknop/I2DM#52]
- Page 52. Proof of Theorem 8.1 "Let z∈Z; we need to find x∈X such that (g◦f)(x) = y" We actually need to find x∈X such that (g◦f)(x) = z.

- Page 53. Proof of Theorem 8.3 "Let us consider the inverse g^(−1) of g. Note that h=f◦g^(−1) is a bijection from [n] to [m]." 

1. h=f◦g^(−1) is not a bijection from [n] to [m]. Rather, h=g^(−1)◦f is a bijection from [n] to [m]. 

2. We can only apply Theorem 8.1 here if g^(-1) is invertible. Although it may be clear to some, consider adding a clarification note that if g is invertible, then g^(-1) is also invertible (perhaps in addition to Theorem 8.2 text).

- Page 53. Corollary 8.1 "cardianlity" is a misspelling of "cardinality."

-Jason Vega (jvega@ucsd.edu)

**Comment by alexanderknop** [comment]
Than you very much!
