### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by OwenPi22** [aaknop/I2DM#6]
1. "(a + b)^2 = (a + b) · (a + b) (by axiom 5)" in the proof in part 1.2: this should be by axiom 6.
2. later on in the proof in part 1.2: "by axiom 1, it is enough to show that (a + b) · (a + b) = a + 2ab + b2.":  a should be also squared
3. in the same proof: "by axiom 3 applied twice, (a + b)·(a + b) = a ·(a + b) + b ·(a + b)..." this is not by axiom 3 only, but by both axioms 3 and 4

Zhiqiang Pi (zhpi@ucsd.edu)

**Comment by alexanderknop** [comment]
Thank you for your comments!
