### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by OwenPi** [aaknop/I2DM#61]
1. in part 11.1 the proof of Theorem 11.1, "ovbious" should be "obvious"
2. in the proof for the Binomial theorem in page 75, "Asume" should be "Assume"
3. in the last part of the proof for the binomial theorem, in the sum. shouldn't it be
    (n+1)+(n+1)
    ( k-1 )    (   k )
4. in exercise 11.3, shouldn't the summation start at i=0
5. in exercise 11.4,it should be "show" instead of "shwo"

Zhiqiang Pi (zhpi@ucsd.edu)

**Comment by alexanderknop** [comment]
Thank you!
