### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by OwenPi** [aaknop/I2DM#62]
1. in exercise 11.5, shouldn't the summation start from 1?
2. in the list of symbols, "denotes the number of ways to choose a subset of n elements from a fixed set of n elements" should be "denotes the number of ways to choose a subset of n elements from a fixed set of m elements"
3. Suggestion, in the list of symbols, when explaining the multiplication sign, maybe use * rather than the dot.
4. in the Logical Notation part, for the first two statements, maybe be consistent on the use of alpha and a.
5. in the set notations, (B)A should be the number of injections from A to B instead of infunctions
6. in theorem 11.3, is the third theorem wrong since there is no m in the right-hand side?
7. in the practice final, the solution for question 5, in the last sentence, you misspelled "answer"

Zhiqiang Pi (zhpi@ucsd.edu)

**Comment by OwenPi** [comment]
> 1. in exercise 11.5, shouldn't the summation start from 1?
> 2. also, can you specify the notation in exercise 11.13?
> 3. in the list of symbols, "denotes the number of ways to choose a subset of n elements from a fixed set of n elements" should be "denotes the number of ways to choose a subset of n elements from a fixed set of m elements"
> 4. Suggestion, in the list of symbols, when explaining the multiplication sign, maybe use * rather than the dot.
> 5. in the Logical Notation part, for the first two statements, maybe be consistent on the use of alpha and a.
> 
> Zhiqiang Pi ([zhpi@ucsd.edu](mailto:zhpi@ucsd.edu))

**Comment by OwenPi** [comment]
shouldn't have closed it, sorry

**Comment by alexanderknop** [comment]
Thank you!
