### ISSUE TITLE
Issue with the list of symbols

### ISSUE THREAD

**Issue by haleydahl** [aaknop/I2DM#64]
I believe that in the descriptions of the notation for (m)n and m choose n it says "denotes the number of ways to choose an subset of n elements from a fixed set of n elements" 

where it should say "a" subset. AND it should say "from a fixed set of **m** elements" for both of the first 2 counting symbols. 

Thanks! 
Haley Dahlberg (A13433190)

**Comment by alexanderknop** [comment]
Thank you!
