### ISSUE TITLE
End of chapter exercises

### ISSUE THREAD

**Issue by jason-vega** [aaknop/I2DM#7]
For exercise 1.7 ("Prove that 0 divides an integer a iff a = 0"), is the question actually intending to ask us to prove that 0 is divisible by an integer a iff a does _not_ equal 0?

Jason Vega (jvega@ucsd.edu)

**Comment by alexanderknop** [comment]
No, you need to show the statement which is stated in the exercise. You need to show that if there is a number b such that 0b = a, then a = 0.
