### ISSUE TITLE
Some typos found in Ch8

### ISSUE THREAD

**Issue by gary317680** [aaknop/I2DM#73]
Student name: Gary Peng
PID: A15103364
Date of submission: 04/11/2019
Note: corrected parts are bolded.

Ch8, p.63:
  In the proof of theorem 8.1, the construction of h'': [n] -> [m-1] should say
  h''(i) = h'(i)     if h'(i) < **h'(n+1)**
           = h'(i) - 1 otherwise

Then, in proving h'' as a bijection, the first bullet point:
    ...If **h'(i1), h'(i2)** < h'(n+1) or **h'(i1), h'(i2)** >= h'(n+1), then ... 
    ...without loss of generality we may assume that h'(i1) < **h'(n+1)** < h'(i2)...

Ch8, p.64:
  In the proof of Corollary 8.1, the bijective function should map from
  **X to [n]** instead of [n]->X because g1(Y)={ f(x): x E Y } has to be a subset of [n].

**Comment by alexanderknop** [comment]
Thank you!
