### ISSUE TITLE
Page 101 Fixes

### ISSUE THREAD

**Issue by bryan-hatton** [aaknop/I2DM#75]
I focused on one page and included reasons for grammatical changes. There is context around the change to make it easy to search and replace.

Spelling:
"not that difficult but very technicall" -> "technical"
" if a propositional formula is a tautlogy" -> "tautology" 
" Consider a tautlogy" -> "tautology"
"The proof of this tautology" -> "tautology"
"consider casess using" -> "cases"

Grammar:
"So the proof simply bruteforce all the values of the variables of a formula and check that the formula is indeed true" -> "brute-forces" and "checks"
Third-person singular noun "proof" needs pluralized verb

" First we derive  A ∨ ¬ A and B ∨ ¬ B, we use these" -> "B, and we use these"
Independent clauses require ", and", ";", or "." (or any other cordinating conjunction)

"After that we consider" -> "After that, we consider"
"Thus we just need" -> "Thus, we just need"
"After that we consider" -> "After that, we consider"
" In this case the assumption" -> "In this case, the assumption"
Introductory phrases need a comma

"the case when A is true but and B is false" -> "A is true and B is false"
This is a compound subordinate clause, which makes things a little tricky. No comma is necessary even though "A is true" and "B is false" are complete sentences.

" is also false, thus the proof" -> "is also false; thus, the proof"
"Thus" is a conjunctive adverb, not a coordinating conjunction. Something else must be used to join the independent clauses, the semicolon in this case.

Cheers,
Bryan Hatton
Contact me if you need more identifying information, like student ID

**Comment by alexanderknop** [comment]
Hi Bryan,

Thank you very much for your feedback! I think your name is enough.
