### ISSUE TITLE
Chapter 12 Page 88: S(n, n-2)

### ISSUE THREAD

**Issue by lichengh** [aaknop/I2DM#77]
Under definition 12.1: Let us find the value in a more complicated setting, we claim that S(n, n − 2) = (n2).
I believe the claim should be S(n, n − 1) = (n2) because this is the actual claim that is proved in the next sentence. Also because S(n, n − 2) = (n2) is not true.

**Comment by alexanderknop** [comment]
This issue was corrected three days ago, however, thank you for your comment.
