### ISSUE TITLE
Page 90 Issue

### ISSUE THREAD

**Issue by KrystopherWeeton** [aaknop/I2DM#79]
Corollary 12.1 states for all positive integers n and k, the number of compositions of n into k is equal to n choose k. The textbook notes that the number of compositions of n into k parts is (n-1) choose (k-1), which is in line with the statement that the number of compositions of n is equal to 2^{n-1}

Problem 2: Page 90 Definition 12.3, "If, in addition, all the numbers are positive, the sequence is called composition" should read "the sequence is called a composition"

**Comment by alexanderknop** [comment]
Thank you!
