### ISSUE TITLE
Some typos and unclear parts found in Ch13

### ISSUE THREAD

**Issue by gary317680** [aaknop/I2DM#89]
Student name: Gary Peng
PID: A15103364
Date of submission: 04/30/2019
Note: corrected parts are **bolded** if possible

Ch13, p.93
  In the third paragraph,
  "Every permutation can **be** uniquely determined by..."

Ch13, p.95
  (A)The first paragraph under "13.3 Permutations with Restricted Cycle Strucutre"
  The permutation 23154 should have canonical cyclic form **(3,1,2)(5,4)**.
  (B)So, under "Lemma 13.1",
  "For exmaple, G(23154) = **31254** and G-1(23154) = (2)(3,1)(5,4) = **32154**" 
***Note: I am unsure if you intended to write a one-line notation for G-1(23154) or perhaps 
  you intended to say that (2)(3,1)(5,4) and (3,1)(5,4) are equivalent. Are they equivalent?

Ch13, p.96
  In "Definition 13.3", it states that "i" is in the set [l-n], but "i" should also be allowed 
  to be 0, otherwise the subsequence W1,W2,...Wn is not accounted for.

Ch13, p.97
  On the side, the URL does not work.

Ch13, p.98
  (A)The first paragraph. From the example given, {12345, 23451...}, it seems that the
  definition of a 1-cycle class should be "...a subset {p1,...,pn} ⊆Sn such that p_k+1(n) = p_k(1)
  and **p_k+1(i-1) = p_k(i), for i ∈ {2,3...n}.**" rather than p_k+1(i+1) = p_k(i).
  (B)Then, in the second paragraph:
  "Let us now prove that...where C1(p1,...,pk) is equal to the number of completed 1-cycle
  classes in **p1,...pk**." I am unsure about this definition. What does it mean by "completed" 
  1-cycle classes? Is it different from any 1-cycle classes?

Thank you!

**Comment by alexanderknop** [comment]
Yes, (2)(3,1)(5,4) and (3,1)(5,4) are equivalent but you are right, it is better to write the permutation in the one line notation.

Thank you for your comments!
