### ISSUE TITLE
Page 103 / Page 104

### ISSUE THREAD

**Issue by KrystopherWeeton** [aaknop/I2DM#96]
Page 103 - “note that k is not fixes” should be “note that k is not fixed’ under Products of Generating Functions

Page 103 - “is not suggesting us an explicit formula” should be “does not suggest an explicit formula”.

Page 104 (not sure if this is an error) - Alternates between “he” and “she” for the officer

**Comment by alexanderknop** [comment]
Thank you! I've decided that I will refer to the officer as she everywhere.
