### ISSUE TITLE
Exercise 17.5 is incorrect

### ISSUE THREAD

**Issue by nliittsc** [aaknop/I2DM#99]
If we have _v_ vertices, where v is an integer, then the given solution of
_(1/2)*d_min <= e <= (1/2)*d_max_
is incorrect.

You bound _2e_ above by the sum of _d_max_ and below by the sum of _d_min_ from _1_ to _v_.
This should give an answer of
_(v/2) * d_min <= e <= (v/2) * d_max_.

The current solution is actually not true, it's easy to draw a counter example.

-Nathan Liittschwager, Math 184A

**Comment by alexanderknop** [comment]
You are right, thank you!
